---
title: "MATH 216 Homework 2 Shiny App"
author: "Connor"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(dplyr)
library(babynames)
library(ggplot2movies)
```


## Inputs and Outputs

You can embed Shiny inputs and outputs in your document. Outputs are automatically updated whenever inputs change.  This demonstrates how a standard R plot can be made interactive by wrapping it in the Shiny `renderPlot` function. The `selectInput` and `sliderInput` functions create the input widgets used to drive the plot.

```{r eruptions, echo=FALSE}

library(dplyr)
library(ggplot2movies)
library(ggplot2)
data(movies)

inputPanel(
  radioButtons("genre", label = "Genres", choices = c("Action", "Animation", "Comedy", "Drama", 
                                                      "Documentary", "Romance", "Short"))

)
  
renderPlot({

  movietype <- movies %>%
    select_("rating", "budget", input$genre) %>%
    rename_("movietype" = input$genre) %>%
    filter(movietype==1) %>%
    group_by(budget) %>%
    summarize(avgrate = mean(rating))

  ggplot(movietype, aes(x=budget, y=avgrate)) +
  geom_point(color = "violetred4", alpha = .75, size = 2) +
  geom_smooth(se = FALSE, color = "darkslateblue", size = 2) +
  theme_minimal()+
  scale_x_log10() +
  labs(title="Does the budget of a movie effect its IMDB Rating?", x="Log10(Budget)", y="Rating in IMDB")
  
})
```
